version: "3.8"
services:
  webserver:
    build: Dockerfile-Apache
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    build: Dockerfile-Database

  worker:
    build: Dockerfile-Worker
    depends_on:
      - db